services:
  zabbix-db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_INITDB_ARGS: "--character-set-server=utf8mb4 --collation-server=utf8mb4_bin"
      TZ: "${PHP_TZ}"
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_bin"
    ]
    volumes:
      - /var/lib/zabbix/mysql:/var/lib/mysql
      - ./part.sql:/docker-entrypoint-initdb.d/part.sql
      - /etc/localtime:/etc/localtime:ro
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.5
    restart: always

  zabbix-server:
    build:
      context: .
      dockerfile: Dockerfile.zabbix-server
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: "zabbix-db"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      ZBX_DEBUGLEVEL: 3
      ZBX_STARTPINGERS: 10
      ZBX_STARTPOLLERPROCESSES: 10
      ZBX_STARTDBSYNCERS: 8
      ZBX_STARTREPORTWRITERS: 5
      ZBX_CACHESIZE: 512M
      ZBX_HISTORYCACHESIZE: 512M
      ZBX_HISTORYINDEXCACHESIZE: 512M
      ZBX_TRENDCACHESIZE: 256M
      ZBX_VALUECACHESIZE: 256M
      ZBX_TIMEOUT: 30
      ZBX_UNREACHABLEPERIOD: 300
      ZBX_UNAVAILABLEDELAY: 60
      ZBX_UNREACHABLEDELAY: 60
      ZBX_STARTBROWSERPOLLERS: 5
      ZBX_STARTLLDWORKERS: 5
      ZBX_HANODENAME: "${ZBX_HANODENAME}"
      ZBX_NODEADDRESS: "172.18.0.8:10051"
      ZBX_WEBSERVICEURL: "http://zabbix-web-service:10053/report"
      ZBX_WEBDRIVERURL: "http://localhost:4444"
      ZBX_TLSCONNECT: psk
      ZBX_TLSACCEPT: psk
      ZBX_TLSPSKIDENTITY: "${ZBX_SRV_PRIMARY_TLSPSKIDENTITY}"
      ZBX_TLSPSKFILE: /var/lib/zabbix/zabbix-server/enc/zabbix_server.psk
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/zabbix/mysql:/var/lib/mysql
      - /var/lib/zabbix/zabbix-server/enc:/var/lib/zabbix/zabbix-server/enc
      - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - "10051:10051"
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.8
    restart: always

  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:ubuntu-latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: "zabbix-db"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      ZBX_SERVER_HOST: "${ZBX_SERVER_HOST}"
      PHP_TZ: "${PHP_TZ}"
      TZ: "${PHP_TZ}"
    depends_on:
      - zabbix-db
      - zabbix-server
    ports:
      - "8080:8080"
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.9
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro

  zabbix-proxy:
    build:
      context: .
      dockerfile: Dockerfile.zabbix-proxy
    container_name: zabbix-proxy
    environment:
      ZBX_PROXYMODE: 0
      ZBX_SERVER_HOST: "${ZBX_SERVER_HOST}"
      ZBX_SERVER_PORT: 10051
      ZBX_HOSTNAME: "${ZBX_PROXY_HOSTNAME}"
      ZBX_DEBUGLEVEL: 3
      ZBX_ENABLEREMOTECOMMANDS: 1
      ZBX_PROXYLOCALBUFFER: 2
      ZBX_PROXYOFFLINEBUFFER: 6
      ZBX_PROXYHEARTBEATFREQUENCY: 10
      ZBX_CONFIGFREQUENCY: 10
      ZBX_DATASENDERFREQUENCY: 1
      ZBX_STARTHISTORYPOLLERS: 5
      ZBX_STARTPOLLERS: 30
      ZBX_STARTPREPROCESSORS: 5
      ZBX_STARTPOLLERSUNREACHABLE: 10
      ZBX_STARTPINGERS: 5
      ZBX_STARTDISCOVERERS: 5
      ZBX_STARTHTTPPOLLERS: 5
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_STARTVMWARECOLLECTORS: 1
      ZBX_CACHESIZE: 1024M
      ZBX_STARTDBSYNCERS: 4
      ZBX_HISTORYCACHESIZE: 1024M
      ZBX_HISTORYINDEXCACHESIZE: 256M
      ZBX_STARTBROWSERPOLLERS: 5
      ZBX_STARTLLDWORKERS: 5
      ZBX_TIMEOUT: 30
      ZBX_UNREACHABLEPERIOD: 20
      ZBX_UNAVAILABLEDELAY: 20
      ZBX_UNREACHABLEDELAY: 20
      ZBX_LOGSLOWQUERIES: 3000
      ZBX_TLSCONNECT: psk
      ZBX_TLSACCEPT: psk
      ZBX_TLSPSKIDENTITY: "${ZBX_PROXY_TLSPSKIDENTITY}"
      ZBX_TLSPSKFILE: zabbix_proxy.psk
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/zabbix/zabbix-proxy/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - /var/lib/zabbix/zabbix-proxy/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts
      - /var/lib/zabbix/zabbix-proxy/enc:/var/lib/zabbix/enc
      - /var/lib/zabbix/zabbix-proxy/mibs:/var/lib/zabbix/mibs
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.13
    restart: always

  zabbix-agent-server:
    build:
      context: .
      dockerfile: Dockerfile.zabbix-agent
    container_name: zabbix-agent-server
    environment:
      ZBX_HOSTNAME: "${ZBX_SERVER_HOST}"
      ZBX_SERVER_HOST: "${ZBX_SERVER_HOST}"
    depends_on:
      - zabbix-server
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.10
    restart: always

  zabbix-agent-db:
    build:
      context: .
      dockerfile: Dockerfile.zabbix-agent
    container_name: zabbix-agent-db
    environment:
      ZBX_HOSTNAME: "zabbix-db"
      ZBX_SERVER_HOST: "${ZBX_SERVER_HOST}"
    depends_on:
      - zabbix-server
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.11
    restart: always

  zabbix-agent-web:
    build:
      context: .
      dockerfile: Dockerfile.zabbix-agent
    container_name: zabbix-agent-web
    environment:
      ZBX_HOSTNAME: "zabbix-web"
      ZBX_SERVER_HOST: "${ZBX_SERVER_HOST}"
    depends_on:
      - zabbix-server
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.12
    restart: always

  zabbix-agent-proxy:
    build:
      context: .
      dockerfile: Dockerfile.zabbix-agent
    container_name: zabbix-agent-proxy
    environment:
      ZBX_HOSTNAME: "${ZBX_PROXY_HOSTNAME}"
      ZBX_SERVER_HOST: "${ZBX_SERVER_HOST}"
    depends_on:
      - zabbix-proxy
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.14
    restart: always

networks:
  zabbix-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
