services:
  zabbix-agent-server:
    image: zabbix/zabbix-agent2:ubuntu-trunk
    container_name: zabbix-server-agent
    environment:
      ZBX_SERVER_HOST: "zabbix-server"
      ZBX_SERVER_PORT: 10051
      ZBX_HOSTNAME: "zabbix-server-agent"
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.10
    deploy:
      resources:
        limits:
          memory: 50M
          cpus: "0.2"
    restart: always

  zabbix-agent-db:
    image: zabbix/zabbix-agent2:ubuntu-trunk
    container_name: zabbix-db-agent
    environment:
      ZBX_SERVER_HOST: "zabbix-server"
      ZBX_SERVER_PORT: 10051
      ZBX_HOSTNAME: "zabbix-db-agent"
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.6
    deploy:
      resources:
        limits:
          memory: 50M
          cpus: "0.2"
    restart: always

  zabbix-agent-web:
    image: zabbix/zabbix-agent2:ubuntu-trunk
    container_name: zabbix-web-agent
    environment:
      ZBX_SERVER_HOST: "zabbix-server"
      ZBX_SERVER_PORT: 10051
      ZBX_HOSTNAME: "zabbix-web-agent"
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.11
    deploy:
      resources:
        limits:
          memory: 50M
          cpus: "0.2"
    restart: always

networks:
  zabbix-net:
    name: zabbix_zabbix-net