services:
  zabbix-server:
    build:
      context: .
      dockerfile: Dockerfile.zabbix-server
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: "${DB_SERVER_HOST_IP}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      ZBX_DEBUGLEVEL: 3
      ZBX_STARTPINGERS: 10
      ZBX_STARTPOLLERS: 5
      ZBX_STARTIPMIPOLLERS: 2
      ZBX_STARTCONNECTORS: 2
      ZBX_STARTPOLLERSUNREACHABLE: 5
      ZBX_STARTTRAPPERS: 5
      ZBX_STARTDISCOVERERS: 10
      ZBX_STARTHISTORYPOLLERS: 5
      ZBX_STARTHTTPPOLLERS: 10
      ZBX_STARTODBCPOLLERS: 5
      ZBX_STARTTIMERS: 1
      ZBX_STARTESCALATORS: 1
      ZBX_JAVAGATEWAY: "${ZBX_SERVER_HOST}"
      ZBX_JAVAGATEWAYPORT: 10052
      ZBX_STARTJAVAPOLLERS: 5
      ZBX_STARTLLDPROCESSORS: 2
      ZBX_STARTPOLLERPROCESSES: 10
      ZBX_STARTDBSYNCERS: 8
      ZBX_STARTREPORTWRITERS: 3
      ZBX_CACHESIZE: 512M
      ZBX_HISTORYCACHESIZE: 512M
      ZBX_HISTORYINDEXCACHESIZE: 512M
      ZBX_TRENDCACHESIZE: 256M
      ZBX_TRENDFUNCTIONCACHESIZE: 128M
      ZBX_VALUECACHESIZE: 256M
      ZBX_TIMEOUT: 5
      ZBX_UNREACHABLEPERIOD: 300
      ZBX_UNREACHABLEDELAY: 60
      ZBX_STARTBROWSERPOLLERS: 5
      ZBX_STARTLLDWORKERS: 5
      ZBX_STARTVMWARECOLLECTORS: 0
      ZBX_VMWAREFREQUENCY: 60
      ZBX_VMWAREPERFFREQUENCY: 60
      ZBX_VMWARECACHESIZE: 256M
      ZBX_STARTPROXYPOLLERS: 5
      ZBX_ENABLEGLOBALSCRIPTS: 1
      ZBX_PROXYCONFIGFREQUENCY: 5
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
      ZBX_PROBLEMHOUSEKEEPINGFREQUENCY: 60
      ZBX_CACHEUPDATEFREQUENCY: 10
      ZBX_VMWARETIMEOUT: 5
      ZBX_HANODENAME: "${ZBX_HANODENAME}"
      ZBX_WEBSERVICEURL: "http://${ZBX_FRONT_HOST}:10053/report"
      ZBX_WEBDRIVERURL: "http://${ZBX_WEBDRIVE_HOST}:4444"
      ZBX_TLSCONNECT: psk
      ZBX_TLSACCEPT: psk
      ZBX_TLSPSKIDENTITY: "${ZBX_SRV_PRIMARY_TLSPSKIDENTITY}"
      ZBX_TLSPSKFILE: /var/lib/zabbix/zabbix-server/enc/zabbix_server.psk
      ZBX_ALERTSCRIPTPATH: "/usr/lib/zabbix/alertscripts"
      ZBX_EXTERNALSCRIPTPATH: "/usr/lib/zabbix/externalscripts"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/zabbix/zabbix-server/enc:/var/lib/zabbix/zabbix-server/enc
      - /var/lib/zabbix/zabbix-server/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - /var/lib/zabbix/zabbix-server/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts
    ports:
      - "10051:10051"
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.8
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10051"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  zabbix-web-service:
    build:
      context: .
      dockerfile: Dockerfile.zabbix-web-service
    container_name: zabbix-web-service
    environment:
      TZ: America/Sao_Paulo
      ZBX_ALLOWEDIP: 0.0.0.0/0
      ZBX_TIMEOUT: 30
      ZBX_STARTREPORTWRITERS: 2
    ports:
      - "${ZBX_FRONT_HOST}:10053:10053"
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./web_service.conf:/etc/zabbix/web_service.conf:ro
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
        reservations:
          memory: 256M
          cpus: "0.5"
    restart: unless-stopped

  zabbix-agent-server:
    image: zabbix/zabbix-agent2:ubuntu-${ZBX_VERSION}-latest
    container_name: zabbix-agent-server
    environment:
      ZBX_SERVER_HOST: "zabbix-server"
      ZBX_SERVER_PORT: 10051
      ZBX_HOSTNAME: "zabbix-server"
      TZ: "${PHP_TZ}"
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.10
    deploy:
      resources:
        limits:
          memory: 50M
          cpus: "0.2"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  zabbix-agent-webservice:
    image: zabbix/zabbix-agent2:ubuntu-$ZBX_VERSION-latest
    container_name: zabbix-agent-web
    environment:
      ZBX_SERVER_HOST: "zabbix-server"
      ZBX_SERVER_PORT: 10051
      ZBX_HOSTNAME: "zabbix-web-agent"
      TZ: "${PHP_TZ}"
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.11
    deploy:
      resources:
        limits:
          memory: 50M
          cpus: "0.2"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

networks:
  zabbix-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
