services:
  zabbix-web-service:
    build:
      context: .  # Diretório atual onde o Dockerfile está localizado
      dockerfile: Dockerfile.zabbix-web-service
    container_name: zabbix-web-service
    environment:
      TZ: America/Sao_Paulo                # Configuração de fuso horário
      ZBX_ALLOWEDIP: 192.168.0.0/24        # Rede permitida para comunicação
      ZBX_TIMEOUT: 30                      # Timeout para relatórios
      ZBX_STARTREPORTWRITERS: 2            # Número de escritores de relatório
    ports:
      - "${ZBX_FRONT_HOST:-127.0.0.1}:10053:10053"  # Porta vinculada ao IP específico (com valor padrão)
    cap_add:
      - SYS_ADMIN                          # Permissões adicionais para o contêiner
    volumes:
      - ./web_service.conf:/etc/zabbix/web_service.conf:ro  # Arquivo de configuração personalizado (somente leitura)
    deploy:
      resources:
        limits:
          memory: 512M                     # Limite máximo de memória
          cpus: "1.0"                      # Limite máximo de CPU
        reservations:
          memory: 256M                     # Memória reservada para o serviço
          cpus: "0.5"                      # CPU reservada para o serviço
    restart: unless-stopped                # Reiniciar, exceto se manualmente parado
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
networks:
  default:
    driver: bridge
