services:
  zabbix-web-service:
    build:
      context: .  # Diretório atual onde o Dockerfile está localizado
      dockerfile: Dockerfile.zabbix-web-service
    container_name: zabbix-web-service
    environment:
      TZ: America/Sao_Paulo
      ZBX_ALLOWEDIP: 172.20.0.0/16,192.168.0.0/24  # Inclui a sub-rede do Docker e a rede local
      ZBX_TIMEOUT: 30
      ZBX_STARTREPORTWRITERS: 2
    ports:
      - "${ZBX_FRONT_HOST}:10053:10053"
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./web_service.conf:/etc/zabbix/web_service.conf:ro
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
        reservations:
          memory: 256M
          cpus: "0.5"
    restart: unless-stopped
