services:
  selenium-event-bus:
    image: selenium/event-bus:${SELENIUM_VERSION}
    container_name: selenium-event-bus
    restart: always
    ports:
      - "${EVENT_BUS_PORT_1}:4442"
      - "${EVENT_BUS_PORT_2}:4443"
      - "5557:5557"
    mem_limit: 128m  # Limita o consumo total de memória para o Event Bus

  selenium-sessions:
    image: selenium/sessions:${SELENIUM_VERSION}
    container_name: selenium-sessions
    restart: always
    ports:
      - "${SESSIONS_PORT}:5556"
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=${EVENT_BUS_PORT_1}
      - SE_EVENT_BUS_SUBSCRIBE_PORT=${EVENT_BUS_PORT_2}
    mem_limit: 128m  # Limita o consumo total de memória para Sessions

  selenium-session-queue:
    image: selenium/session-queue:${SELENIUM_VERSION}
    container_name: selenium-session-queue
    restart: always
    ports:
      - "${SESSION_QUEUE_PORT}:5559"
    mem_limit: 128m  # Limita o consumo total de memória para Session Queue

  selenium-distributor:
    image: selenium/distributor:${SELENIUM_VERSION}
    container_name: selenium-distributor
    restart: always
    ports:
      - "${DISTRIBUTOR_PORT}:5553"
    depends_on:
      - selenium-event-bus
      - selenium-sessions
      - selenium-session-queue
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=${EVENT_BUS_PORT_1}
      - SE_EVENT_BUS_SUBSCRIBE_PORT=${EVENT_BUS_PORT_2}
      - SE_SESSIONS_MAP_HOST=selenium-sessions
      - SE_SESSIONS_MAP_PORT=${SESSIONS_PORT}
      - SE_SESSION_QUEUE_HOST=selenium-session-queue
      - SE_SESSION_QUEUE_PORT=${SESSION_QUEUE_PORT}
    mem_limit: 128m  # Limita o consumo total de memória para o Distributor

  selenium-router:
    image: selenium/router:${SELENIUM_VERSION}
    container_name: selenium-router
    restart: always
    ports:
      - "${ROUTER_PORT}:4444"
    depends_on:
      - selenium-distributor
      - selenium-sessions
      - selenium-session-queue
    environment:
      - SE_DISTRIBUTOR_HOST=selenium-distributor
      - SE_DISTRIBUTOR_PORT=${DISTRIBUTOR_PORT}
      - SE_SESSIONS_MAP_HOST=selenium-sessions
      - SE_SESSIONS_MAP_PORT=${SESSIONS_PORT}
      - SE_SESSION_QUEUE_HOST=selenium-session-queue
      - SE_SESSION_QUEUE_PORT=${SESSION_QUEUE_PORT}
    mem_limit: 128m  # Limita o consumo total de memória para o Router

  chrome:
    image: selenium/node-chrome:${SELENIUM_VERSION}
    shm_size: 2gb  # Memória compartilhada para o navegador
    restart: always
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=${EVENT_BUS_PORT_1}
      - SE_EVENT_BUS_SUBSCRIBE_PORT=${EVENT_BUS_PORT_2}
      - SE_NODE_MAX_SESSIONS=1  # Limita a 1 sessão por navegador
      - SE_NODE_HEADLESS=true  # Modo headless para reduzir consumo
    mem_limit: 512m  # Limita o consumo total de memória para o Chrome

  edge:
    image: selenium/node-edge:${SELENIUM_VERSION}
    shm_size: 2gb  # Memória compartilhada para o navegador
    restart: always
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=${EVENT_BUS_PORT_1}
      - SE_EVENT_BUS_SUBSCRIBE_PORT=${EVENT_BUS_PORT_2}
      - SE_NODE_MAX_SESSIONS=1  # Limita a 1 sessão por navegador
      - SE_NODE_HEADLESS=true  # Modo headless para reduzir consumo
    mem_limit: 512m  # Limita o consumo total de memória para o Edge

  firefox:
    image: selenium/node-firefox:${SELENIUM_VERSION}
    shm_size: 2gb  # Memória compartilhada para o navegador
    restart: always
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=${EVENT_BUS_PORT_1}
      - SE_EVENT_BUS_SUBSCRIBE_PORT=${EVENT_BUS_PORT_2}
      - SE_NODE_MAX_SESSIONS=1  # Limita a 1 sessão por navegador
      - SE_NODE_HEADLESS=true  # Modo headless para reduzir consumo
    mem_limit: 512m  # Limita o consumo total de memória para o Firefox
