services:
  zabbix-proxy:
    build:
      context: .
      dockerfile: Dockerfile.zabbix-proxy
    container_name: zabbix-proxy
    environment:
      ZBX_PROXYMODE: 0
      ZBX_SERVER_HOST: "${ZBX_SERVER_HOST}"
      ZBX_SERVER_PORT: 10051
      ZBX_HOSTNAME: "${ZBX_PROXY_HOSTNAME}"
      ZBX_DEBUGLEVEL: 3
      ZBX_ENABLEREMOTECOMMANDS: 1
      ZBX_PROXYLOCALBUFFER: 2
      ZBX_PROXYOFFLINEBUFFER: 12
      ZBX_PROXYHEARTBEATFREQUENCY: 10
      ZBX_CONFIGFREQUENCY: 10
      ZBX_DATASENDERFREQUENCY: 1
      ZBX_STARTHISTORYPOLLERS: 10
      ZBX_STARTPOLLERS: 10
      ZBX_STARTPREPROCESSORS: 10
      ZBX_STARTPOLLERSUNREACHABLE: 20
      ZBX_STARTPINGERS: 10
      ZBX_STARTDISCOVERERS: 10
      ZBX_STARTHTTPPOLLERS: 10
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_STARTVMWARECOLLECTORS: 2
      ZBX_CACHESIZE: 2048M
      ZBX_STARTDBSYNCERS: 6
      ZBX_HISTORYCACHESIZE: 2048M
      ZBX_HISTORYINDEXCACHESIZE: 512M
      ZBX_STARTBROWSERPOLLERS: 10
      ZBX_STARTLLDWORKERS: 10
      ZBX_TIMEOUT: 30
      ZBX_UNREACHABLEPERIOD: 30
      ZBX_UNAVAILABLEDELAY: 30
      ZBX_UNREACHABLEDELAY: 30
      ZBX_LOGSLOWQUERIES: 3000
      ZBX_TLSCONNECT: psk
      ZBX_TLSACCEPT: psk
      ZBX_TLSPSKIDENTITY: "${ZBX_PROXY_TLSPSKIDENTITY}"
      ZBX_TLSPSKFILE: zabbix_proxy.psk
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/zabbix/zabbix-proxy/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - /var/lib/zabbix/zabbix-proxy/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts
      - /var/lib/zabbix/zabbix-proxy/enc:/var/lib/zabbix/enc
      - /var/lib/zabbix/zabbix-proxy/mibs:/var/lib/zabbix/mibs
      - ./my.cnf:/etc/mysql/my.cnf
    network_mode: "host"  # Usando a rede local do host
    restart: always
