services:
  zabbix-proxy-db:
    image: mysql:8.0.30
    container_name: zabbix-proxy-db
    restart: always
    environment:
      MYSQL_DATABASE: zabbix_proxy               # Nome do banco de dados
      MYSQL_USER: zabbix-proxy                   # Usuário do banco
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"        # Senha do banco (definida no .env)
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"  # Senha root (definida no .env)
    command:
      - mysqld
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_bin
    volumes:
      - /data/zabbix/zabbix-proxy/mysql:/var/lib/mysql  # Persistência de dados do MySQL
      - /etc/localtime:/etc/localtime:ro               # Sincronizar fuso horário
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.20                      # IP fixo na rede Zabbix

  zabbix-proxy:
    build:
      context: .                                        # Diretório atual
      dockerfile: Dockerfile.zabbix-proxy-mysql         # Dockerfile customizado
    container_name: zabbix-proxy
    environment:
      ZBX_PROXYMODE: 0                                 # Modo ativo (0) ou passivo (1)
      ZBX_SERVER_HOST: "${ZBX_SERVER_HOST}"            # IP ou hostname do servidor Zabbix
      ZBX_SERVER_PORT: 10051                           # Porta do servidor Zabbix
      ZBX_HOSTNAME: "${ZBX_PROXY_BALTIMORE_MYSQL_HOSTNAME}"  # Nome do proxy
      ZBX_DEBUGLEVEL: 3                                # Nível de debug
      ZBX_ENABLEREMOTECOMMANDS: 1                      # Permitir comandos remotos
      ZBX_PROXYLOCALBUFFER: 2                          # Buffer local (horas)
      ZBX_PROXYOFFLINEBUFFER: 12                       # Buffer offline (horas)
      ZBX_PROXYHEARTBEATFREQUENCY: 10                  # Frequência de heartbeat (segundos)
      ZBX_CONFIGFREQUENCY: 10                          # Frequência de configuração (segundos)
      ZBX_DATASENDERFREQUENCY: 1                       # Frequência de envio de dados (segundos)
      ZBX_STARTHISTORYPOLLERS: 10                      # Pollers de histórico
      ZBX_STARTPOLLERS: 10                             # Pollers gerais
      ZBX_STARTPREPROCESSORS: 10                       # Pré-processadores
      ZBX_STARTPOLLERSUNREACHABLE: 20                  # Pollers de hosts inatingíveis
      ZBX_STARTPINGERS: 10                             # Ping pollers
      ZBX_STARTDISCOVERERS: 10                         # Descobridores
      ZBX_STARTHTTPPOLLERS: 10                         # HTTP pollers
      ZBX_STARTODBCPOLLERS: 5                          # ODBC pollers
      ZBX_HOUSEKEEPINGFREQUENCY: 1                     # Frequência de limpeza (horas)
      ZBX_STARTVMWARECOLLECTORS: 2                     # Coletores VMware
      ZBX_CACHESIZE: 256M                              # Cache principal
      ZBX_STARTDBSYNCERS: 6                            # Sincronizadores de banco
      ZBX_HISTORYCACHESIZE: 256M                       # Cache de histórico
      ZBX_HISTORYINDEXCACHESIZE: 256M                  # Cache de índice de histórico
      ZBX_WEBDRIVERURL: "http://${ZBX_WEBDRIVE_HOST}:4444"  # URL do WebDriver
      ZBX_STARTBROWSERPOLLERS: 10                      # Pollers de navegador
      ZBX_STARTLLDWORKERS: 10                          # LLD workers
      ZBX_TIMEOUT: 30                                  # Timeout geral
      ZBX_UNREACHABLEPERIOD: 30                        # Período para hosts inatingíveis
      ZBX_UNAVAILABLEDELAY: 30                         # Atraso para hosts indisponíveis
      ZBX_UNREACHABLEDELAY: 30                         # Atraso para hosts inatingíveis
      ZBX_LOGSLOWQUERIES: 3000                         # Log de queries lentas (ms)
      ZBX_TLSCONNECT: psk                              # Conexão TLS (PSK)
      ZBX_TLSACCEPT: psk                               # Aceitar conexões TLS (PSK)
      ZBX_TLSPSKIDENTITY: "${ZBX_PROXY_BALTIMORE_MYSQL_TLSPSKIDENTITY}"  # Identidade PSK
      ZBX_TLSPSKFILE: "/var/lib/zabbix/enc/${ZBX_PROXY_BALTIMORE_MYSQL_TLSPSKIDENTITY}.psk"  # Arquivo PSK
      DB_SERVER_HOST: 172.18.0.20                      # Host do banco de dados
      MYSQL_DATABASE: zabbix_proxy                     # Nome do banco
      MYSQL_USER: zabbix-proxy                         # Usuário do banco
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"              # Senha do banco (do .env)
    volumes:
      - /var/lib/zabbix/zabbix-proxy/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - /var/lib/zabbix/zabbix-proxy/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts
      - /var/lib/zabbix/zabbix-proxy-mysql/enc:/var/lib/zabbix/enc
      - /etc/localtime:/etc/localtime:ro
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.21                      # IP fixo do proxy
    depends_on:
      - zabbix-proxy-db                                # Inicia o banco antes do proxy
    restart: always                                    # Reinicia em caso de falha
    logging:
      driver: json-file                                # Configuração de logs
      options:
        max-size: "10m"                                # Limite de tamanho por log
        max-file: "3"                                  # Número máximo de arquivos de log

networks:
  zabbix-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16                        # Subnet da rede Zabbix
