services:
  zabbix-proxy:
    build:
      context: .
      dockerfile: Dockerfile.zabbix-proxy
    container_name: zabbix-proxy-baltimore
    environment:
      ZBX_PROXYMODE: 0
      ZBX_SERVER_HOST: "${ZBX_SERVER_HOST}"
      ZBX_SERVER_PORT: 10051
      ZBX_HOSTNAME: "${ZBX_PROXY_BALTIMORE_HOSTNAME}"
      ZBX_DEBUGLEVEL: 3
      ZBX_ENABLEREMOTECOMMANDS: 1
      ZBX_PROXYLOCALBUFFER: 2
      ZBX_PROXYOFFLINEBUFFER: 6
      ZBX_PROXYHEARTBEATFREQUENCY: 10
      ZBX_CONFIGFREQUENCY: 10
      ZBX_DATASENDERFREQUENCY: 1
      ZBX_STARTHISTORYPOLLERS: 5
      ZBX_STARTPOLLERS: 30
      ZBX_STARTPREPROCESSORS: 5
      ZBX_STARTPOLLERSUNREACHABLE: 10
      ZBX_STARTPINGERS: 5
      ZBX_STARTDISCOVERERS: 5
      ZBX_STARTHTTPPOLLERS: 5
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_STARTVMWARECOLLECTORS: 1
      ZBX_CACHESIZE: 128M
      ZBX_STARTDBSYNCERS: 4
      ZBX_HISTORYCACHESIZE: 128M
      ZBX_HISTORYINDEXCACHESIZE: 128M
      ZBX_STARTBROWSERPOLLERS: 5
      ZBX_STARTLLDWORKERS: 5
      ZBX_TIMEOUT: 30
      ZBX_UNREACHABLEPERIOD: 20
      ZBX_UNAVAILABLEDELAY: 20
      ZBX_UNREACHABLEDELAY: 20
      ZBX_LOGSLOWQUERIES: 3000
      ZBX_TLSCONNECT: psk
      ZBX_TLSACCEPT: psk
      ZBX_TLSPSKIDENTITY: "${ZBX_PROXY_BALTIMORE_TLSPSKIDENTITY}"
      ZBX_TLSPSKFILE: "/var/lib/zabbix/enc/${ZBX_PROXY_BALTIMORE_TLSPSKIDENTITY}.psk"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/zabbix/zabbix-proxy/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - /var/lib/zabbix/zabbix-proxy/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts
      - /var/lib/zabbix/zabbix-proxy/enc:/var/lib/zabbix/enc
      - /var/lib/zabbix/zabbix-proxy/mibs:/var/lib/zabbix/mibs
      - ./my.cnf:/etc/mysql/my.cnf
    network_mode: "host"  # Usando a rede local do host
    restart: always