services:
  zabbix-proxy-db:
    image: mysql:8.0.30
    container_name: zabbix-proxy-db
    restart: always
    environment:
      MYSQL_DATABASE: zabbix_proxy
      MYSQL_USER: zabbix-proxy
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    command:
      - mysqld
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_bin
    volumes:
      - /data/zabbix/zabbix-proxy/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.20

  zabbix-proxy:
    build:
      context: .
      dockerfile: Dockerfile.zabbix-proxy-mysql
    container_name: zabbix-proxy
    environment:
      ZBX_PROXYMODE: 0
      ZBX_SERVER_HOST: "${ZBX_SERVER_HOST}"
      ZBX_SERVER_PORT: 10051
      ZBX_HOSTNAME: "${ZBX_PROXY_BALTIMORE_MYSQL_HOSTNAME}"
      ZBX_DEBUGLEVEL: 3
      ZBX_ENABLEREMOTECOMMANDS: 1
      ZBX_PROXYLOCALBUFFER: 2
      ZBX_PROXYOFFLINEBUFFER: 12
      ZBX_PROXYHEARTBEATFREQUENCY: 10
      ZBX_CONFIGFREQUENCY: 10
      ZBX_DATASENDERFREQUENCY: 1
      ZBX_STARTHISTORYPOLLERS: 10
      ZBX_STARTPOLLERS: 10
      ZBX_STARTPREPROCESSORS: 10
      ZBX_STARTPOLLERSUNREACHABLE: 20
      ZBX_STARTPINGERS: 10
      ZBX_STARTDISCOVERERS: 10
      ZBX_STARTHTTPPOLLERS: 10
      ZBX_STARTODBCPOLLERS: 5
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_STARTVMWARECOLLECTORS: 2
      ZBX_CACHESIZE: 256M
      ZBX_STARTDBSYNCERS: 6
      ZBX_HISTORYCACHESIZE: 256M
      ZBX_HISTORYINDEXCACHESIZE: 256M
      ZBX_WEBDRIVERURL: "http://${ZBX_WEBDRIVE_HOST}:4444"
      ZBX_STARTBROWSERPOLLERS: 10
      ZBX_STARTLLDWORKERS: 10
      ZBX_TIMEOUT: 30
      ZBX_UNREACHABLEPERIOD: 30
      ZBX_UNAVAILABLEDELAY: 30
      ZBX_UNREACHABLEDELAY: 30
      ZBX_LOGSLOWQUERIES: 3000
      ZBX_TLSCONNECT: psk
      ZBX_TLSACCEPT: psk
      ZBX_TLSPSKIDENTITY: "${ZBX_PROXY_BALTIMORE_MYSQL_TLSPSKIDENTITY}"
      ZBX_TLSPSKFILE: "/var/lib/zabbix/enc/${ZBX_PROXY_BALTIMORE_MYSQL_TLSPSKIDENTITY}.psk"
      DB_SERVER_HOST: 172.18.0.20
      MYSQL_DATABASE: zabbix_proxy
      MYSQL_USER: zabbix-proxy
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - /var/lib/zabbix/zabbix-proxy/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - /var/lib/zabbix/zabbix-proxy/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts
      - /var/lib/zabbix/zabbix-proxy-mysql/enc:/var/lib/zabbix/enc
      - /etc/localtime:/etc/localtime:ro
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.21
    depends_on:
      - zabbix-proxy-db
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  zabbix-agent-db:
    image: zabbix/zabbix-agent2:ubuntu-latest
    container_name: zabbix-agent-db
    environment:
      ZBX_SERVER_HOST: 172.18.0.21  # Enviar dados para o zabbix-proxy
      ZBX_SERVER_PORT: 10051
      ZBX_HOSTNAME: "zabbix-proxy-db-agent"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.22
    depends_on:
      - zabbix-proxy  # Garantir que o proxy esteja em execução
    restart: always

  zabbix-agent-proxy:
    image: zabbix/zabbix-agent2:ubuntu-latest
    container_name: zabbix-agent-proxy
    environment:
      ZBX_SERVER_HOST: 172.18.0.21  # Enviar dados para o zabbix-proxy
      ZBX_SERVER_PORT: 10051
      ZBX_HOSTNAME: "zabbix-proxy-agent"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.23
    depends_on:
      - zabbix-proxy  # Garantir que o proxy esteja em execução
    restart: always

networks:
  zabbix-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
