services:
  zabbix-agent-server:
    build:
      context: .
      dockerfile: Dockerfile.zabbix-agent
    container_name: zabbix-agent-server
    environment:
      ZBX_HOSTNAME: "${ZBX_SERVER_HOST}"
      ZBX_SERVER_HOST: "${ZBX_SERVER_HOST}"
    depends_on:
      - zabbix-server
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.10
    restart: always

  zabbix-agent-db:
    build:
      context: .
      dockerfile: Dockerfile.zabbix-agent
    container_name: zabbix-agent-db
    environment:
      ZBX_HOSTNAME: "zabbix-db"
      ZBX_SERVER_HOST: "${ZBX_SERVER_HOST}"
    depends_on:
      - zabbix-server
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.11
    restart: always

  zabbix-agent-web:
    build:
      context: .
      dockerfile: Dockerfile.zabbix-agent
    container_name: zabbix-agent-web
    environment:
      ZBX_HOSTNAME: "zabbix-web"
      ZBX_SERVER_HOST: "${ZBX_SERVER_HOST}"
    depends_on:
      - zabbix-server
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.12
    restart: always

  zabbix-agent-proxy:
    build:
      context: .
      dockerfile: Dockerfile.zabbix-agent
    container_name: zabbix-agent-proxy
    environment:
      ZBX_HOSTNAME: "${ZBX_PROXY_HOSTNAME}"
      ZBX_SERVER_HOST: "${ZBX_SERVER_HOST}"
    depends_on:
      - zabbix-proxy
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.14
    restart: always

networks:
  zabbix-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
