services:
  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:ubuntu-latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: "${DB_SERVER_HOST_IP}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      ZBX_SERVER_HOST: "${ZBX_SERVER_HOST}"
      PHP_TZ: "${PHP_TZ}"
      TZ: "${PHP_TZ}"
    ports:
      - "8080:8080"
    network_mode: "host"  # Usando a rede local do host
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro

