services:
  zabbix-agent:
    image: zabbix/zabbix-agent2:7.0-alpine-latest
    container_name: "${ZBX_AGENT_BOSTON_HOSTNAME}"
    environment:
      ZBX_HOSTNAME: "${ZBX_AGENT_BOSTON_HOSTNAME}"
      ZBX_SERVER_HOST: "${ZBX_PROXY_HOST}"  # IP do proxy (ou servidor)
      ZBX_SERVER_PORT: "10051"
      ZBX_TIMEOUT: "30"
      ZBX_TLSCONNECT: "unencrypted"    # Sem TLS
      ZBX_TLSACCEPT: "unencrypted"     # Sem TLS
    network_mode: "host"               # Usando rede local do host
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro