# Dockerfile.zabbix-agent
FROM zabbix/zabbix-agent2:ubuntu-7.0-latest

USER root

# Configurar o fuso horário
ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN mkdir -p /var/lib/apt/lists/partial && \
    chmod -R 755 /var/lib/apt/lists && \
    apt-get update && \
    apt-get install -y nano vim htop && \
    rm -rf /var/lib/apt/lists/*

USER zabbix
