services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "${PORTAINER_HTTP_PORT:-8000}:8000"
      - "${PORTAINER_HTTPS_PORT:-9443}:9443"
    environment:
      TZ: "${TZ:-America/Sao_Paulo}" # Define o timezone para o contêiner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - portainer_net
    mem_limit: 1G
    cpus: "2.0"

networks:
  portainer_net:
    driver: bridge

volumes:
  portainer_data:
