services:
  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:ubuntu-7.0-latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: "${DB_SERVER_HOST_IP}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      ZBX_SERVER_HOST: "${ZBX_SERVER_HOST}"
      PHP_TZ: "${PHP_TZ}"
      TZ: "${PHP_TZ}"
    depends_on:
      - zabbix-server
    ports:
      - "8080:8080"
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.9
    volumes:
      - /etc/localtime:/etc/localtime:ro

    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/zabbix"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  zabbix-agent-web:
    image: zabbix/zabbix-agent2:ubuntu-7.0-latest
    container_name: zabbix-agent-web
    environment:
      ZBX_SERVER_HOST: "${ZBX_SERVER_HOST}"
      ZBX_SERVER_PORT: 10051
      ZBX_HOSTNAME: "zabbix-web-agent"
      TZ: "${PHP_TZ}"
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.11
    deploy:
      resources:
        limits:
          memory: 50M
          cpus: "0.2"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  grafana:
    build:
      context: .
      dockerfile: Dockerfile.Grafana
      args:
        TZ: ${PHP_TZ}
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - TZ=${PHP_TZ}
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_logs:/var/log/grafana
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "0.5"
        reservations:
          memory: 512M
          cpus: "0.3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    depends_on:
      - zabbix-server

  zabbix-agent-grafana:
    image: zabbix/zabbix-agent2:ubuntu-7.0-latest
    container_name: zabbix-agent-grafana
    environment:
      ZBX_SERVER_HOST: "${ZBX_SERVER_HOST}"
      ZBX_SERVER_PORT: 10051
      ZBX_HOSTNAME: "grafana-agent"
      TZ: "${PHP_TZ}"
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.12
    deploy:
      resources:
        limits:
          memory: 50M
          cpus: "0.2"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

volumes:
  grafana_data:
  grafana_logs:

networks:
  zabbix-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
