services:
  zabbix-db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_INITDB_ARGS: "--character-set-server=utf8mb4 --collation-server=utf8mb4_bin"
      TZ: "${PHP_TZ}"
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_bin"
    ]
    volumes:
      - /var/lib/zabbix/mysql:/var/lib/mysql
      - ./part.sql:/docker-entrypoint-initdb.d/part.sql
      - ./create_users.sql:/docker-entrypoint-initdb.d/create_users.sql  # Novo arquivo para criar usuários
      - /etc/localtime:/etc/localtime:ro
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      zabbix-net:
        ipv4_address: 172.18.0.5
    restart: always

networks:
  zabbix-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
