services:
  zabbix-db:
    container_name: zabbix-db
    build:
      context: .
      dockerfile: Dockerfile.zabbix-partition
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_INITDB_ARGS: "--character-set-server=utf8mb4 --collation-server=utf8mb4_bin"
      TZ: "${PHP_TZ}"
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_bin"
    ]
    volumes:
      - /var/lib/zabbix/mysql:/var/lib/mysql
      - ./part.sql:/docker-entrypoint-initdb.d/part.sql
      - ./create_users.sql:/docker-entrypoint-initdb.d/create_users.sql
      - /etc/localtime:/etc/localtime:ro
      - ./my.cnf:/etc/mysql/my.cnf
      - /var/log/mysql:/var/log/mysql
    ports:
      - "3306:3306"  # Mapeamento explícito
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: "2.0"
        reservations:
          memory: 2G
