services:
  zabbix-db:
    container_name: zabbix-db  # Nome fixo para o container
    build:
      context: .
      dockerfile: Dockerfile.zabbix-partition
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_INITDB_ARGS: "--character-set-server=utf8mb4 --collation-server=utf8mb4_bin"
      TZ: "${PHP_TZ}"
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_bin"
    ]
    volumes:
      - /var/lib/zabbix/mysql:/var/lib/mysql
      - ./part.sql:/docker-entrypoint-initdb.d/part.sql  # Mantido para particionamento
      - ./create_users.sql:/docker-entrypoint-initdb.d/create_users.sql  # Novo arquivo para criar usuários
      - /etc/localtime:/etc/localtime:ro
      - ./my.cnf:/etc/mysql/my.cnf
      - /var/log/mysql:/var/log/mysql  # Logs do MySQL
    network_mode: "host"  # Utilizando a rede local do host
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
